language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - phpenv config-add dev/dev.ini
  - composer global require hirak/prestissimo

install:
  - composer install

script:
  - ./dev/qa.sh
